# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7330fc05dda010bd69bc34f256143b6e394815bb00d79780a1b2e6d22064e979c5ff81f0bf3f4fc8e90c3e2886acc4cd06e72707e5de996f718c3c5d158056f8

test:
  secret_key_base: 4709384b8b56d868c9f8d5eddd896ac59c6956981afbad9695cd5292048c3ebdd619bdb9c26037d50b8d0471ebb453a4260ee811caaaa7984a6a329c456d6fc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
